export const LOGIN_PATH = '/login'
export const COUPLES_PATH = '/couples'
export const DISCOVER_PATH = '/discover'
export const ACCOUNT_PATH = '/account'
export const USER_PATH = '/user'
export const CHAT_PATH = '/chat/:id'